/**
 * FROZEN PURE-DATA CONFIG — immutable once fan-out has started.
 * Do not add functions, environment reads, computed defaults, or credential values.
 */

import type {
  BenchmarkSuiteId,
  ByteCount,
  CredentialEnvName,
  DurationMs,
  OmegaConfig,
  TokenCount,
} from "../contracts/index.js";

export const DEFAULT_CONFIG: Readonly<OmegaConfig> = {
  schemaVersion: 1,
  homeDirectory: {
    kind: "user-home-relative",
    path: ".omega",
  },
  server: {
    host: "127.0.0.1",
    port: 7337,
    bearerTokenEnvName: "OMEGA_API_TOKEN" as CredentialEnvName,
  },
  storage: {
    fsyncEvents: true,
    objectHash: "sha256",
    sessionRetentionDays: null,
  },
  processes: {
    maxConcurrent: 8,
    liveChunkBytes: 65_536 as ByteCount,
    gracefulShutdownMs: 5_000 as DurationMs,
    orphanPolicy: "verify-and-terminate",
    sandboxBackend: "auto",
  },
  models: {
    providers: [
      {
        providerId: "openrouter",
        adapter: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        credentialEnvName: "OPENROUTER_API_KEY" as CredentialEnvName,
      },
    ],
    routes: [
      {
        role: "main-coder",
        providerId: "openrouter",
        modelId: "nvidia/nemotron-3-ultra-550b-a55b:free",
        reasoning: { mode: "effort", effort: "high" },
        selection: {
          kind: "openrouter",
          mode: "balanced",
          providerOrder: [],
          allowFallbacks: true,
          requireParameters: true,
          dataCollection: "deny",
          zeroDataRetention: null,
        },
        temperature: null,
        topP: null,
        seed: null,
        maxOutputTokens: 32_768 as TokenCount,
        timeoutMs: 300_000 as DurationMs,
      },
      {
        role: "fast-policy",
        providerId: "openrouter",
        modelId: "nvidia/nemotron-3-ultra-550b-a55b:free",
        reasoning: { mode: "off" },
        selection: {
          kind: "openrouter",
          mode: "balanced",
          providerOrder: [],
          allowFallbacks: true,
          requireParameters: true,
          dataCollection: "deny",
          zeroDataRetention: null,
        },
        temperature: 0,
        topP: null,
        seed: null,
        maxOutputTokens: 1_024 as TokenCount,
        timeoutMs: 30_000 as DurationMs,
      },
      {
        role: "harness-mutator",
        providerId: "openrouter",
        modelId: "nvidia/nemotron-3-ultra-550b-a55b:free",
        reasoning: { mode: "effort", effort: "high" },
        selection: {
          kind: "openrouter",
          mode: "balanced",
          providerOrder: [],
          allowFallbacks: true,
          requireParameters: true,
          dataCollection: "deny",
          zeroDataRetention: null,
        },
        temperature: null,
        topP: null,
        seed: null,
        maxOutputTokens: 32_768 as TokenCount,
        timeoutMs: 300_000 as DurationMs,
      },
      {
        role: "promotion-evaluator",
        providerId: "openrouter",
        modelId: "nvidia/nemotron-3-ultra-550b-a55b:free",
        reasoning: { mode: "effort", effort: "high" },
        selection: {
          kind: "openrouter",
          mode: "exacto",
          providerOrder: [],
          allowFallbacks: false,
          requireParameters: true,
          dataCollection: "deny",
          zeroDataRetention: null,
        },
        temperature: 0,
        topP: null,
        seed: null,
        maxOutputTokens: 16_384 as TokenCount,
        timeoutMs: 300_000 as DurationMs,
      },
      {
        role: "diagnostician",
        providerId: "openrouter",
        modelId: "nvidia/nemotron-3-ultra-550b-a55b:free",
        reasoning: { mode: "effort", effort: "high" },
        selection: {
          kind: "openrouter",
          mode: "balanced",
          providerOrder: [],
          allowFallbacks: true,
          requireParameters: true,
          dataCollection: "deny",
          zeroDataRetention: null,
        },
        temperature: null,
        topP: null,
        seed: null,
        maxOutputTokens: 16_384 as TokenCount,
        timeoutMs: 300_000 as DurationMs,
      },
      {
        role: "crystallizer",
        providerId: "openrouter",
        modelId: "nvidia/nemotron-3-ultra-550b-a55b:free",
        reasoning: { mode: "effort", effort: "high" },
        selection: {
          kind: "openrouter",
          mode: "balanced",
          providerOrder: [],
          allowFallbacks: true,
          requireParameters: true,
          dataCollection: "deny",
          zeroDataRetention: null,
        },
        temperature: null,
        topP: null,
        seed: null,
        maxOutputTokens: 16_384 as TokenCount,
        timeoutMs: 300_000 as DurationMs,
      },
    ],
  },
  policy: {
    profile: "guarded",
    uncertainty: "deny",
    policyRole: "fast-policy",
  },
  benchmarks: {
    developmentSuiteId: "omegabench-10@1" as BenchmarkSuiteId,
    maxConcurrentRuns: 1,
    fallbackBudget: null,
  },
};
