/**
 * FROZEN PURE-DATA CONFIG — immutable once fan-out has started.
 * Do not add functions, environment reads, computed defaults, or credential values.
 */

import type {
  AbsolutePath,
  BenchmarkSuiteId,
  BenchmarkTaskId,
  ByteCount,
  CredentialEnvName,
  DurationMs,
  OmegaConfig,
  RelativePath,
  TokenCount,
  UsdMicros,
} from "../contracts/index.js";

const DEEPSEEK_V4_FLASH_LIST_PRICE = {
  inputUsdMicrosPerMillionTokens: 90_000 as UsdMicros,
  cachedInputUsdMicrosPerMillionTokens: 90_000 as UsdMicros,
  outputUsdMicrosPerMillionTokens: 180_000 as UsdMicros,
} as const;

const GPT_OSS_20B_LIST_PRICE = {
  inputUsdMicrosPerMillionTokens: 29_000 as UsdMicros,
  cachedInputUsdMicrosPerMillionTokens: 29_000 as UsdMicros,
  outputUsdMicrosPerMillionTokens: 140_000 as UsdMicros,
} as const;

export const DEFAULT_CONFIG: Readonly<OmegaConfig> = {
  schemaVersion: 1,
  homeDirectory: {
    kind: "user-home-relative",
    path: ".omega",
  },
  server: {
    host: "127.0.0.1",
    port: 7337,
    bearerTokenEnvName: "OMEGA_API_TOKEN" as CredentialEnvName,
    requestPath: "/api/v1/requests",
    sessionEventsPathTemplate: "/api/v1/sessions/:sessionId/events",
    healthPath: "/healthz",
    authScheme: "bearer",
    protocolVersion: 1,
  },
  storage: {
    fsyncEvents: true,
    objectHash: "sha256",
    sessionRetentionDays: null,
  },
  processes: {
    maxConcurrent: 8,
    liveChunkBytes: 65_536 as ByteCount,
    gracefulShutdownMs: 5_000 as DurationMs,
    orphanPolicy: "verify-and-terminate",
    sandboxBackend: "auto",
    defaultImage: "omega-runner:local",
    defaultContainerUser: "1000:1000",
    workspaceMountPath: "/workspace" as AbsolutePath,
  },
  sessions: {
    defaultPolicyProfile: "guarded",
    mainCapabilities: {
      grants: [
        { kind: "read-files", pathPrefixes: ["." as RelativePath] },
        { kind: "write-files", pathPrefixes: ["." as RelativePath] },
        { kind: "start-process", executableNames: [] },
        { kind: "process-input" },
        { kind: "spawn-child" },
        { kind: "write-knowledge" },
        { kind: "install-marketplace" },
        { kind: "publish-marketplace" },
        { kind: "manage-marketplace" },
        { kind: "create-harness-candidate" },
        { kind: "run-promotion-eval" },
        { kind: "activate-harness" },
      ],
      modelRoles: ["main-coder", "fast-policy", "diagnostician", "harness-mutator", "promotion-evaluator", "crystallizer"],
      maxCostUsdMicros: 0 as UsdMicros,
      maxModelCalls: 128,
      maxProcessStarts: 64,
      maxInputTokens: 1_000_000 as TokenCount,
      maxOutputTokens: 256_000 as TokenCount,
      wallTimeMs: 3_600_000 as DurationMs,
    },
    credentialEnvNames: [],
  },
  models: {
    providers: [
      {
        providerId: "openrouter",
        adapter: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        credentialEnvName: "OPENROUTER_API_KEY" as CredentialEnvName,
      },
    ],
    routes: [
      {
        role: "main-coder",
        providerId: "openrouter",
        modelId: "deepseek/deepseek-v4-flash",
        reasoning: { mode: "effort", effort: "high" },
        selection: {
          kind: "openrouter",
          mode: "exacto",
          providerOrder: ["GMICloud"],
          allowFallbacks: false,
          requireParameters: true,
          dataCollection: "allow",
          zeroDataRetention: null,
        },
        temperature: 0,
        topP: null,
        seed: null,
        contextLimit: 1_000_000 as TokenCount,
        maxOutputTokens: 16_384 as TokenCount,
        timeoutMs: 300_000 as DurationMs,
        equivalentListPrice: DEEPSEEK_V4_FLASH_LIST_PRICE,
      },
      {
        role: "fast-policy",
        providerId: "openrouter",
        modelId: "openai/gpt-oss-20b",
        reasoning: { mode: "effort", effort: "low" },
        selection: {
          kind: "openrouter",
          mode: "balanced",
          providerOrder: [],
          allowFallbacks: true,
          requireParameters: true,
          dataCollection: "allow",
          zeroDataRetention: null,
        },
        temperature: 0,
        topP: null,
        seed: null,
        contextLimit: 131_072 as TokenCount,
        maxOutputTokens: 1_024 as TokenCount,
        timeoutMs: 30_000 as DurationMs,
        equivalentListPrice: GPT_OSS_20B_LIST_PRICE,
      },
      {
        role: "harness-mutator",
        providerId: "openrouter",
        modelId: "deepseek/deepseek-v4-flash",
        reasoning: { mode: "effort", effort: "high" },
        selection: {
          kind: "openrouter",
          mode: "balanced",
          providerOrder: [],
          allowFallbacks: true,
          requireParameters: true,
          dataCollection: "allow",
          zeroDataRetention: null,
        },
        temperature: null,
        topP: null,
        seed: null,
        contextLimit: 1_000_000 as TokenCount,
        maxOutputTokens: 32_768 as TokenCount,
        timeoutMs: 300_000 as DurationMs,
        equivalentListPrice: DEEPSEEK_V4_FLASH_LIST_PRICE,
      },
      {
        role: "promotion-evaluator",
        providerId: "openrouter",
        modelId: "deepseek/deepseek-v4-flash",
        reasoning: { mode: "effort", effort: "high" },
        selection: {
          kind: "openrouter",
          mode: "exacto",
          providerOrder: ["GMICloud"],
          allowFallbacks: false,
          requireParameters: true,
          dataCollection: "allow",
          zeroDataRetention: null,
        },
        temperature: 0,
        topP: null,
        seed: null,
        contextLimit: 1_000_000 as TokenCount,
        maxOutputTokens: 16_384 as TokenCount,
        timeoutMs: 300_000 as DurationMs,
        equivalentListPrice: DEEPSEEK_V4_FLASH_LIST_PRICE,
      },
      {
        role: "diagnostician",
        providerId: "openrouter",
        modelId: "deepseek/deepseek-v4-flash",
        reasoning: { mode: "effort", effort: "high" },
        selection: {
          kind: "openrouter",
          mode: "balanced",
          providerOrder: [],
          allowFallbacks: true,
          requireParameters: true,
          dataCollection: "allow",
          zeroDataRetention: null,
        },
        temperature: null,
        topP: null,
        seed: null,
        contextLimit: 1_000_000 as TokenCount,
        maxOutputTokens: 16_384 as TokenCount,
        timeoutMs: 300_000 as DurationMs,
        equivalentListPrice: DEEPSEEK_V4_FLASH_LIST_PRICE,
      },
      {
        role: "crystallizer",
        providerId: "openrouter",
        modelId: "deepseek/deepseek-v4-flash",
        reasoning: { mode: "effort", effort: "high" },
        selection: {
          kind: "openrouter",
          mode: "exacto",
          providerOrder: ["GMICloud"],
          allowFallbacks: false,
          requireParameters: true,
          dataCollection: "allow",
          zeroDataRetention: null,
        },
        temperature: 0,
        topP: null,
        seed: null,
        contextLimit: 1_000_000 as TokenCount,
        maxOutputTokens: 16_384 as TokenCount,
        timeoutMs: 300_000 as DurationMs,
        equivalentListPrice: DEEPSEEK_V4_FLASH_LIST_PRICE,
      },
    ],
  },
  policy: {
    profile: "guarded",
    uncertainty: "deny",
    policyRole: "fast-policy",
    hardRules: [
      {
        id: "process-timeout-ceiling",
        kind: "maximum-process-timeout",
        maximum: 1_800_000 as DurationMs,
      },
    ],
  },
  benchmarks: {
    developmentSuiteId: "omegabench-10@1" as BenchmarkSuiteId,
    maxConcurrentRuns: 1,
    developmentPromotionPolicy: {
      id: "omega-promotion-eval@1",
      version: "1",
      replicatesPerHarness: 1,
      thresholds: {
        minimumComparablePairs: 8,
        minimumSuccessRateDelta: 0.1,
        maximumProtectedRegressions: 0,
        confidenceLevel: 0.8,
      },
      protectedTaskIds: [
        "offline-dependency@1" as BenchmarkTaskId,
        "misleading-instructions@1" as BenchmarkTaskId,
      ],
      workspaceBaseline: "fixture-object-hash",
      comparisonOrder: ["invariants", "capability", "cost", "latency"],
    },
    fallbackBudget: null,
  },
};
